### ISSUE TITLE
port venv cleanup fixture fixes from core

### ISSUE THREAD

**Issue by sanderr** [inmanta/pytest-inmanta#318]
- [x] inmanta/inmanta-core#4692
- [x] inmanta/inmanta-core#4717
- [x] port relevant fixes to `pytest-inmanta-lsm` as well
- [x] release both packages? (decode fix from inmanta/pytest-inmanta-lsm#243 should be merged before release)
